[package]
name = "liblinphone-sys"
version = "0.1.0"
authors = ["Jon Lamb"]
edition = "2018"
links = "linphone_sys"
build = "build.rs"

[build-dependencies]
bindgen = "0.49.2"
cmake = "0.1.40"

[dependencies]
